# Generated by Django 5.2.1 on 2025-06-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='benesse',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
