# Generated by Django 5.2.1 on 2025-08-04 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField()),
                ('uuid', models.CharField()),
                ('title', models.CharField()),
                ('status', models.IntegerField()),
                ('folder_name', models.CharField()),
                ('folder_number', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('title', models.CharField()),
                ('type', models.CharField()),
                ('video_time_seconds', models.FloatField()),
                ('average_answer_time_seconds', models.FloatField()),
                ('total_answered', models.IntegerField()),
                ('total_correctly_answered', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stats.video')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField()),
                ('total_views', models.IntegerField()),
                ('started_views', models.IntegerField()),
                ('finished_views', models.IntegerField()),
                ('passed_views', models.IntegerField()),
                ('failed_views', models.IntegerField()),
                ('unfinished_views', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stats.video')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.IntegerField()),
                ('title', models.CharField()),
                ('type', models.CharField()),
                ('action_type', models.CharField()),
                ('start_time_seconds', models.FloatField()),
                ('end_time_seconds', models.FloatField()),
                ('duration_seconds', models.FloatField()),
                ('link', models.CharField()),
                ('total_clicks', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stats.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_id', models.IntegerField()),
                ('average_rating', models.FloatField()),
                ('one_star', models.IntegerField()),
                ('two_star', models.IntegerField()),
                ('three_star', models.IntegerField()),
                ('four_star', models.IntegerField()),
                ('five_star', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stats.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField()),
                ('started_views', models.IntegerField()),
                ('finished_views', models.IntegerField()),
                ('interaction_clicks', models.IntegerField()),
                ('video_duration_seconds', models.FloatField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stats.video')),
            ],
        ),
        migrations.CreateModel(
            name='ViewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('started_time_unix', models.IntegerField()),
                ('ended_time_unix', models.IntegerField()),
                ('viewer_timezone', models.CharField()),
                ('viewer_os', models.CharField()),
                ('viewer_browser', models.CharField()),
                ('viewer_mobile', models.BooleanField()),
                ('last_reached_seconds', models.IntegerField()),
                ('last_reached_percent', models.FloatField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stats.video')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField()),
                ('answered_count', models.IntegerField()),
                ('is_correct_answer', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stats.questionstats')),
            ],
            options={
                'unique_together': {('question', 'label')},
            },
        ),
    ]
