# Generated by Django 5.2.1 on 2025-06-23 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField()),
                ('uuid', models.CharField()),
                ('title', models.CharField()),
                ('status', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField()),
                ('total_views', models.IntegerField()),
                ('started_views', models.IntegerField()),
                ('finished_views', models.IntegerField()),
                ('passed_views', models.IntegerField()),
                ('failed_views', models.IntegerField()),
                ('unfinished_views', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stats.video')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.IntegerField()),
                ('title', models.CharField()),
                ('type', models.CharField()),
                ('action_type', models.CharField()),
                ('start_time_seconds', models.FloatField()),
                ('end_time_seconds', models.FloatField()),
                ('duration_seconds', models.FloatField()),
                ('link', models.CharField()),
                ('total_clicks', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stats.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField()),
                ('started_views', models.IntegerField()),
                ('finished_views', models.IntegerField()),
                ('interaction_clicks', models.IntegerField()),
                ('video_duration_seconds', models.FloatField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stats.video')),
            ],
        ),
    ]
