# Generated by Django 5.2.1 on 2025-06-26 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_id', models.IntegerField()),
                ('average_rating', models.FloatField()),
                ('one_star', models.IntegerField()),
                ('two_star', models.IntegerField()),
                ('three_star', models.IntegerField()),
                ('four_star', models.IntegerField()),
                ('five_star', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stats.video')),
            ],
        ),
    ]
