# Generated by Django 5.2.1 on 2025-06-27 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stats', '0002_videorating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('started_time_unix', models.IntegerField()),
                ('ended_time_unix', models.IntegerField()),
                ('viewer_timezone', models.CharField()),
                ('viewer_os', models.CharField()),
                ('viewer_browser', models.CharField()),
                ('viewer_mobile', models.BooleanField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stats.video')),
            ],
        ),
    ]
