# Generated by Django 5.2.1 on 2025-06-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stats', '0003_viewsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewsession',
            name='last_reached_percent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewsession',
            name='last_reached_seconds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
