# Generated by Django 5.2.1 on 2025-07-04 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stats', '0004_viewsession_last_reached_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('title', models.CharField()),
                ('type', models.CharField()),
                ('video_time_seconds', models.FloatField()),
                ('average_answer_time_seconds', models.FloatField()),
                ('total_answered', models.IntegerField()),
                ('total_correctly_answered', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stats.video')),
            ],
        ),
    ]
